In [1]:
print("Model for Prediction of Doctor's fees")

Model for Prediction of Doctor's fees

In [2]:
import pandas as pd
import math
from sklearn.model_selection import train_test_split
print("Packages imported")

Packages imported

In [3]:
DataCols = ['Qualification','Experience','Rating','Place','Profile','Miscellaneous_Info']
DocData = pd.read_csv('DocTest.csv',names=DataCols)
DocData = DocData[1:]
DocData.dropna()
Tdata = DocData['Profile']
Qclasses = ['MD','MBBS','BHMS','BAMS','BDS','MDS','Get inspired by remarkable stories of people like you','LCEH','GCEH','BSAM','DDVL','DDV','DNB','G.A.M.S','DLO','M.D.','Diploma in Dermatology','PhD']
Plclasses = ['Ernakulam','Bangalore','Chennai','Hyderabad','Coimbatore','Delhi','Mumbai','Thiruvananthapuram']
Prclasses = ['Homeopath','Dentist','Ayurveda','ENT Specialist','Dermatologists','General Medicine']
print(DocData)

                                          Qualification           Experience  \
1                                                  MBBS  35 years experience
2            MBBS, Diploma in Otorhinolaryngology (DLO)  31 years experience
3                                            MBBS, DDVL  40 years experience
4                                                  BAMS   0 years experience
5       BDS, MDS - Conservative Dentistry & Endodontics  16 years experience
6                                              BDS, MDS  14 years experience
7            MBBS, Diploma in Otorhinolaryngology (DLO)  23 years experience
8                                BDS, MDS - Pedodontics   9 years experience
9     MD - Ayurveda Medicine, BAMS, Yoga Teachers Tr...  11 years experience
10                                                 BHMS  44 years experience
11                                                  BDS   4 years experience
12                              MBBS, FCD - Diabetology  34 years experience
13                                            MBBS, DDV  11 years experience
14                               MBBS, MD - Dermatology  13 years experience
15                                             MS - ENT   4 years experience
16                                                  BDS   4 years experience
17                               MBBS, MD - Dermatology  16 years experience
18    MBBS, Diploma in Otorhinolaryngology (DLO), MS...  28 years experience
19      BDS, MDS - Conservative Dentistry & Endodontics   6 years experience
20                               MBBS, MD - Dermatology  32 years experience
21    BHMS, Diploma in Naturopathy & Yogic Science (...  11 years experience
22                                                  BDS   3 years experience
23                               MBBS, MD - Dermatology   8 years experience
24     MBBS, PG Diploma In Clinical Cosmetology (PGDCC)  13 years experience
25                                                 MBBS  43 years experience
26           MBBS, Diploma in Otorhinolaryngology (DLO)  27 years experience
27                              BDS, MDS - Periodontics  22 years experience
28                             BDS, MDS- Oral Pathology   8 years experience
29                          MBBS, MD - General Medicine  25 years experience
30                                       MS - ENT, MBBS   4 years experience
...                                                 ...                  ...
1958  MD - Acupuncture, PG Diploma In Clinical Cosme...   8 years experience
1959  MBBS, MS - ENT, Diploma in Otorhinolaryngology...  40 years experience
1960                                MBBS, MD - Medicine  43 years experience
1961                            BDS, MDS - Orthodontics  29 years experience
1962                                               BHMS   2 years experience
1963                                        MBBS, PGDHA  12 years experience
1964                                               BHMS   3 years experience
1965  BDS, MDS - Prosthodontist And Crown Bridge, Ce...   8 years experience
1966                                    MBBS, MRCOG(UK)  35 years experience
1967  MD - Medicine, Post Graduate Diploma in Diabet...  24 years experience
1968                                 MDS - Periodontics  13 years experience
1969                        MBBS, DNB - Family Medicine  23 years experience
1970                       BAMS, MD - Ayurveda Medicine  32 years experience
1971              MDS - Prosthodontist And Crown Bridge   7 years experience
1972                                     MBBS, MS - ENT  26 years experience
1973                       MBBS, Diploma in Dermatology  15 years experience
1974                                          MBBS, DDV   4 years experience
1975         MBBS, Diploma in Otorhinolaryngology (DLO)  19 years experience
1976                                               MBBS  26 years experience
1977                     MBBS, MS - Otorhinolaryngology  11 years experience
1978           MBBS, MS - General Surgery, FAIS, FIAGES  28 years experience
1979                             BDS, MDS - Endodontics  15 years experience
1980            BDS, MDS - Oral & Maxillofacial Surgery  17 years experience
1981                             MDS - Pedodontics, BDS  18 years experience
1982  MBBS, MD - Dermatology , Venereology & Leprosy...   8 years experience
1983                           BAMS, Doctor of Medicine  10 years experience
1984     MD - Dermatology , Venereology & Leprosy, MBBS   4 years experience
1985           MBBS, MD / MS - Obstetrics & Gynaecology   9 years experience
1986                                                BDS  12 years experience
1987     MBBS, MD - Dermatology , Venereology & Leprosy   8 years experience

     Rating                              Place           Profile  \
1       NaN             Ghatkopar East, Mumbai  General Medicine
2       NaN        West Marredpally, Hyderabad    ENT Specialist
3       70%                  KK Nagar, Chennai    Dermatologists
4       NaN             New Ashok Nagar, Delhi          Ayurveda
5      100%          Kanakpura Road, Bangalore           Dentist
6       90%                 Velachery, Chennai           Dentist
7       94%             Frazer Town, Bangalore    ENT Specialist
8       94%                 Attapur, Hyderabad           Dentist
9       99%            Banashankari, Bangalore          Ayurveda
10      NaN            Mayur Vihar Ph-I, Delhi         Homeopath
11     100%               Erragadda, Hyderabad           Dentist
12      NaN            Gandhipuram, Coimbatore  General Medicine
13      98%               Kemps Corner, Mumbai    Dermatologists
14      99%           Banjara Hills, Hyderabad    Dermatologists
15      NaN              Madandapuram, Chennai    ENT Specialist
16      NaN             Mukherjee Nagar, Delhi           Dentist
17      87%                  Tis Hazari, Delhi    Dermatologists
18      64%  Banashankari 2nd Stage, Bangalore    ENT Specialist
19      NaN                Nagawara, Bangalore           Dentist
20      90%            Basavanagudi, Bangalore    Dermatologists
21      NaN                      Dadar, Mumbai         Homeopath
22      NaN      Kattakada, Thiruvananthapuram           Dentist
23      NaN               Villivakkam, Chennai    Dermatologists
24     100%                Begumpet, Hyderabad  General Medicine
25      NaN               Kottivakkam, Chennai  General Medicine
26      NaN              Jeedimetla, Hyderabad    ENT Specialist
27     100%              Gachibowli, Hyderabad           Dentist
28      96%                 Chromepet, Chennai           Dentist
29      NaN                Mulund West, Mumbai  General Medicine
30      NaN               Bellandur, Bangalore    ENT Specialist
...     ...                                ...               ...
1958   100%                    KPHB, Hyderabad           Dentist
1959    53%            Millers Road, Bangalore    ENT Specialist
1960    NaN             Vileparle West, Mumbai  General Medicine
1961    95%              Punjagutta, Hyderabad           Dentist
1962    NaN             Malleswaram, Bangalore         Homeopath
1963   100%                      Rohini, Delhi  General Medicine
1964    NaN               Habsiguda, Hyderabad         Homeopath
1965    NaN         Ramanathapuram, Coimbatore           Dentist
1966    88%                   Choolai, Chennai  General Medicine
1967    NaN                  Tambaram, Chennai  General Medicine
1968    98%               Yelahanka, Bangalore           Dentist
1969    96%             Indiranagar, Bangalore  General Medicine
1970    NaN                    Chembur, Mumbai          Ayurveda
1971    NaN           Sundarapuram, Coimbatore           Dentist
1972    NaN                       Okhla, Delhi    ENT Specialist
1973    93%              Moti Nagar, Hyderabad    Dermatologists
1974    NaN                 Velachery, Chennai    Dermatologists
1975    NaN                     Munirka, Delhi    ENT Specialist
1976    NaN             Panchsheel Park, Delhi  General Medicine
1977    84%                 Miyapur, Hyderabad    ENT Specialist
1978    NaN             Panchsheel Park, Delhi  General Medicine
1979    NaN                 Prabhadevi, Mumbai           Dentist
1980   100%                      Powai, Mumbai           Dentist
1981    98%                 Velachery, Chennai           Dentist
1982    NaN            Lajpat Nagar III, Delhi    Dermatologists
1983    NaN            Basavanagudi, Bangalore          Ayurveda
1984    NaN                   Choolai, Chennai    Dermatologists
1985    NaN                     Porur, Chennai  General Medicine
1986    98%                 Arekere, Bangalore           Dentist
1987    NaN              Pallikaranai, Chennai    Dermatologists

                                     Miscellaneous_Info  Fees
1                                                   NaN   NaN
2                                                   NaN   NaN
3                      70% 4 Feedback KK Nagar, Chennai   NaN
4                                                   NaN   NaN
5     General Dentistry Conservative Dentistry Cosme...   NaN
6     Acrylic Partial Denture Impaction / Impacted T...   NaN
7                 94% 6 Feedback Frazer Town, Bangalore   NaN
8     RCT - Root Canal Treatment Ceramic Veneers / C...   NaN
9              99% 203 Feedback Banashankari, Bangalore   NaN
10                                                  NaN   NaN
11    Dental Fillings Zirconia Crowns RCT - Single S...   NaN
12                                                  NaN   NaN
13                 98% 28 Feedback Kemps Corner, Mumbai   NaN
14    Laser Hair Removal - Face Skin Tag Treatment H...   NaN
15                                                  NaN   NaN
16             Mukherjee Nagar, Delhi ₹250 Visits Today   NaN
17                     87% 9 Feedback Tis Hazari, Delhi   NaN
18     64% 4 Feedback Banashankari 2nd Stage, Bangalore   NaN
19    Ceramic Veneers / Crowns Cosmetic/ Aesthetic D...   NaN
20               90% 3 Feedback Basavanagudi, Bangalore   NaN
21                                                  NaN   NaN
22                                                  NaN   NaN
23                                                  NaN   NaN
24                 100% 10 Feedback Begumpet, Hyderabad   NaN
25                                                  NaN   NaN
26                                                  NaN   NaN
27    Crowns and Bridges Fixing Teeth Whitening Gum ...   NaN
28    Artificial Teeth Conservative Dentistry Crowns...   NaN
29    Balance Exercises Acne / Pimples Treatment Ins...   NaN
30                                                  NaN   NaN
...                                                 ...   ...
1958                   100% 12 Feedback KPHB, Hyderabad   NaN
1959            53% 12 Feedback Millers Road, Bangalore   NaN
1960  Viral Fever Treatment Dengue Fever Treatment T...   NaN
1961  Dental Implant Fixing Invisible/Clear Braces C...   NaN
1962             3 Feedback Malleswaram, Bangalore ₹500   NaN
1963                     100% 23 Feedback Rohini, Delhi   NaN
1964                                                NaN   NaN
1965                                                NaN   NaN
1966                    88% 5 Feedback Choolai, Chennai   NaN
1967                                                NaN   NaN
1968  Gum Disease Treatment/ Surgery Dental Implant ...   NaN
1969             96% 12 Feedback Indiranagar, Bangalore   NaN
1970                                                NaN   NaN
1971                                                NaN   NaN
1972  Endoscopic DCR Sleep related disorders such as...   NaN
1973              93% 36 Feedback Moti Nagar, Hyderabad   NaN
1974  Skin Allergy Treatment Skin Allergies Dermabra...   NaN
1975                                                NaN   NaN
1976  foot and ankle problems 1 Feedback Panchsheel ...   NaN
1977                 84% 20 Feedback Miyapur, Hyderabad   NaN
1978   Panchsheel Park, Delhi ₹1,000 Available Tomorrow   NaN
1979           Prabhadevi, Mumbai ₹1,000 Visits On-Call   NaN
1980  General Dentistry Dental Fillings RCT - Single...   NaN
1981                98% 240 Feedback Velachery, Chennai   NaN
1982                                                NaN   NaN
1983                                                NaN   NaN
1984                                                NaN   NaN
1985                                                NaN   NaN
1986  RCT - Root Canal Treatment Root Canal Treatmen...   NaN
1987              1 Feedback Pallikaranai, Chennai ₹500   NaN

[1987 rows x 7 columns]

In [4]:
# Molding the dataset
QUALS = []
Tdata = DocData['Qualification'].values
Tdata = list(Tdata)

for sample in Tdata:
    Include = []
    for qual in Qclasses:
        if qual in sample:
            Include.append(qual)
    
    NewText = ""
    for I in Include:
        NewText = NewText + I + ","
    
    NewText = NewText[:-1]
    QUALS.append(NewText)

QUALS_F = []
for row in QUALS:
    if row=='':
        QUALS_F.append('MS')
    else:
        QUALS_F.append(row)

# QUALS_F contains the FInal Qualifications to be appended in new dataframe

In [98]:
DocPlaces = []
Tdata = DocData['Place'].values
Tdata = list(Tdata)

for sample in Tdata:
    if sample!=sample:
        DocPlaces.append('Unknown')
    else:
        f=0
        for place in Plclasses:
            if place in sample:
                DocPlaces.append(place)
                f=1
                break
        
        if f==0:
            DocPlaces.append('Unknown')
            
            
#DocPlaces contains Places of Doctors to be appended

In [5]:
DocProfiles = []
Tdata = DocData['Profile'].values
Tdata = list(Tdata)
'''
for sample in Tdata:
    if sample!=sample:
        DocProfiles.append('Unknown')
    else:
        f=0
        for profile in Prclasses:
            if profile in sample:
                DocProfiles.append(profile)
                f=1
                break
        
        if f==0:
            DocProfiles.append('Unknown')
'''
DocProfiles = Tdata
#Doc Profiles are finalized Profiles

In [6]:
Ttdata=DocData['Fees'].values
print(Ttdata)
Fdata = []
for i in Ttdata:
    i = int(i)
    Fdata.append(i)
#Now, we have integers in Fdata list as our Fees

[nan nan nan ... nan nan nan]

ValueError: cannot convert float NaN to integer

In [100]:
Tdata = DocData['Rating'].values
Tdata = list(Tdata)
RatData = []

for sample in Tdata:
    if sample!=sample:
        RatData.append(0)
    else:
        sample  = sample[:-1]
        sample = int(sample)
        RatData.append(sample)

#RatData contains FInal Ratings to be appended

In [101]:
Tdata = DocData['Experience'].values
Tdata = list(Tdata)
ExpData = []

for sample in Tdata:
    sample = sample[:-17]
    temp = int(sample)
    ExpData.append(temp)

    # ExpData stores Exps to be appended

In [103]:
#Now, Creating a new DataFrame
NewDocData = []
DataCols = ['Qualification','Experience','Rating','Place','Profile','Fees']
for i in range(len(Tdata)):
    temp = []
    temp.append(QUALS_F[i])
    temp.append(ExpData[i])
    temp.append(RatData[i])
    temp.append(DocPlaces[i])
    temp.append(DocProfiles[i])
    temp.append(Fdata[i])
    NewDocData.append(temp)


myFrame = pd.DataFrame(NewDocData,columns=DataCols)
myFrame.to_csv('Mtrain.csv')
print(myFrame)

                    Qualification  Experience  Rating               Place  \
0                         MD,BHMS          24     100           Ernakulam
1                         MD,BAMS          12      98           Bangalore
2                            MBBS           9       0           Bangalore
3                            BAMS          12       0           Bangalore
4                            BAMS          20     100             Chennai
5                            BAMS           8       0             Chennai
6                            BHMS          42       0               Delhi
7                             BDS          10      99           Bangalore
8                         MD,MBBS          14       0           Hyderabad
9                             BDS          23       0           Ernakulam
10                       MBBS,DNB           5       0             Chennai
11                           BAMS           7       0           Hyderabad
12                     MD,BDS,MDS           9      98          Coimbatore
13                     MD,BDS,MDS          21       0           Hyderabad
14                   MBBS,DNB,DLO          12       0               Delhi
15                        MD,MBBS          10       0           Hyderabad
16                       MBBS,DLO          24       0             Chennai
17                           MBBS           5       0             Chennai
18                           MBBS          19      79           Hyderabad
19                           MBBS          19     100           Bangalore
20                 MD,BDS,MDS,DNB          21     100          Coimbatore
21                       MBBS,DNB          14       0               Delhi
22                           MBBS          41       0              Mumbai
23                           MBBS          31       0           Ernakulam
24                  MBBS,DDVL,DDV          23       0              Mumbai
25                            BDS           5       0  Thiruvananthapuram
26                           MBBS          25     100           Bangalore
27                        MD,MBBS          12      95           Hyderabad
28                     MD,BDS,MDS          16       0          Coimbatore
29    MBBS,Diploma in Dermatology          15      97               Delhi
...                           ...         ...     ...                 ...
5929                         MBBS          13      99           Bangalore
5930                          BDS           9       0          Coimbatore
5931                      MD,BHMS          21      96           Bangalore
5932                         BHMS          19       0              Mumbai
5933                   MD,BDS,MDS          12      99           Bangalore
5934                      MD,LCEH          34     100              Mumbai
5935                         BHMS          19      96           Bangalore
5936                         MBBS          36       0           Bangalore
5937                      MD,BHMS           7       0              Mumbai
5938                      MD,MBBS          40      80              Mumbai
5939                         BHMS          30       0               Delhi
5940                      MD,MBBS          51      90           Bangalore
5941                          BDS           3      95           Bangalore
5942                           MS           2       0             Chennai
5943                          BDS           4       0             Chennai
5944                          BDS          12      99               Delhi
5945                         BHMS           6       0           Bangalore
5946                         BAMS          15       0              Mumbai
5947                         BHMS           8       0              Mumbai
5948                      MD,MBBS           4     100           Bangalore
5949                          BDS           4       0           Bangalore
5950                         MBBS          47       0              Mumbai
5951                           MD          35      92           Bangalore
5952                         BHMS          31       0               Delhi
5953                           MD          10       0               Delhi
5954                         MBBS          19      98           Bangalore
5955                         MBBS          33       0             Chennai
5956                         MBBS          41      97               Delhi
5957                      MD,MBBS          15      90              Mumbai
5958                   MD,BDS,MDS          17     100               Delhi

      Profile  Fees
0     Unknown   100
1     Unknown   350
2     Unknown   300
3     Unknown   250
4     Unknown   250
5     Unknown   100
6     Unknown   200
7     Unknown   200
8     Unknown   100
9     Unknown   100
10    Unknown   700
11    Unknown   100
12    Unknown   200
13    Unknown   350
14    Unknown   500
15    Unknown   200
16    Unknown   100
17    Unknown   300
18    Unknown   400
19    Unknown   150
20    Unknown   100
21    Unknown   500
22    Unknown   200
23    Unknown   100
24    Unknown   100
25    Unknown   100
26    Unknown   500
27    Unknown   250
28    Unknown   100
29    Unknown   500
...       ...   ...
5929  Unknown   300
5930  Unknown   100
5931  Unknown   500
5932  Unknown   100
5933  Unknown   300
5934  Unknown   100
5935  Unknown   400
5936  Unknown   300
5937  Unknown   400
5938  Unknown   800
5939  Unknown   300
5940  Unknown   450
5941  Dentist   300
5942  Unknown   200
5943  Unknown   150
5944  Dentist   300
5945  Unknown   100
5946  Unknown   100
5947  Unknown   400
5948  Unknown   350
5949  Unknown   200
5950  Unknown   100
5951  Unknown   100
5952  Unknown   300
5953  Unknown   300
5954  Unknown   300
5955  Unknown   100
5956  Unknown   600
5957  Unknown   100
5958  Unknown   200

[5959 rows x 6 columns]

In [104]:
from sklearn.linear_model import LinearRegression  
from sklearn import metrics 
from sklearn.preprocessing import PolynomialFeatures
from keras.models import Sequential
from keras.layers import Flatten,Dense
DataCols = ['Index','Qualification','Experience','Rating','Place','Profile','Fees']
DocData = pd.read_csv('Mtrain.csv',names=DataCols)
X = DocData.iloc[:,1:6].values
X = X[1:]
Y = DocData.iloc[:,-1].values
Y = Y[1:]
Qclasses = ['MD','MBBS','BHMS','BAMS','BDS','MDS','Get inspired by remarkable stories of people like you','LCEH','GCEH','BSAM','DDVL','DDV','DNB','G.A.M.S','DLO','M.D.','Diploma in Dermatology','PhD','MS']
Qweights = [16,15,5,6,7,14,1,8,9,4,10,11,12,2,13,16,3,17,3]
Plclasses = ['Ernakulam','Bangalore','Chennai','Hyderabad','Coimbatore','Delhi','Mumbai','Thiruvananthapuram','Unknown']
Prclasses = ['Homeopath','Dentist','Ayurveda','ENT Specialist','Dermatologists','General Medicine','Unknown']
Plweights = [2,6,3,4,7,8,9,5,1]
Prweights = [7,6,5,4,3,2,1]
Qdict = dict(zip(Qclasses,Qweights))
Pldict = dict(zip(Plclasses,Plweights))
Prdict = dict(zip(Prclasses,Prweights))
for i in range(len(X)):
    split = X[i][0].split(',')
    X[i][0] = 0
    for j in split:
        X[i][0]+=Qdict[j]
    X[i][1] = int(X[i][1])
    X[i][2] = int(X[i][2])
    X[i][3] = Pldict[X[i][3]]
    X[i][4] = Prdict[X[i][4]]
    Y[i] = int(Y[i])

Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,Y,test_size=0.2,random_state=0)
print(Xtrain[:5])
print(Ytrain[:5])

[[21 21 0 4 1]
 [28 34 92 6 1]
 [6 4 0 6 1]
 [15 28 100 3 1]
 [7 5 100 4 1]]
[250 380 200 300 200]

In [105]:
from sklearn.preprocessing import Normalizer
from keras.models import Sequential
from keras.layers import Flatten,Dense
model = Sequential()
model.add(Dense(64, input_dim=5, kernel_initializer='normal', activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
model.fit(Xtrain, Ytrain, epochs=50, batch_size=20,  verbose=1, validation_split=0.1)

Train on 4290 samples, validate on 477 samples
Epoch 1/50
4290/4290 [==============================] - 2s 468us/step - loss: 50100.1114 - acc: 0.0016 - val_loss: 35971.6994 - val_acc: 0.0021
Epoch 2/50
4290/4290 [==============================] - 1s 192us/step - loss: 36811.1543 - acc: 0.0012 - val_loss: 35324.5700 - val_acc: 0.0000e+00
Epoch 3/50
4290/4290 [==============================] - 1s 173us/step - loss: 36399.7709 - acc: 0.0014 - val_loss: 35437.6172 - val_acc: 0.0021
Epoch 4/50
4290/4290 [==============================] - 1s 173us/step - loss: 36505.4863 - acc: 0.0014 - val_loss: 34713.6097 - val_acc: 0.0000e+00
Epoch 5/50
4290/4290 [==============================] - 1s 174us/step - loss: 36137.2406 - acc: 0.0014 - val_loss: 35498.5911 - val_acc: 0.0063
Epoch 6/50
4290/4290 [==============================] - 1s 186us/step - loss: 36163.0117 - acc: 0.0023 - val_loss: 34815.3391 - val_acc: 0.0000e+00
Epoch 7/50
4290/4290 [==============================] - 1s 173us/step - loss: 35865.1297 - acc: 0.0014 - val_loss: 34504.5278 - val_acc: 0.0042
Epoch 8/50
4290/4290 [==============================] - 1s 178us/step - loss: 35710.6139 - acc: 0.0028 - val_loss: 34172.1335 - val_acc: 0.0063
Epoch 9/50
4290/4290 [==============================] - 1s 180us/step - loss: 35477.9659 - acc: 0.0014 - val_loss: 34487.6345 - val_acc: 0.0084
Epoch 10/50
4290/4290 [==============================] - 1s 185us/step - loss: 35278.3578 - acc: 0.0023 - val_loss: 35906.4206 - val_acc: 0.0021
Epoch 11/50
4290/4290 [==============================] - 1s 182us/step - loss: 35438.8949 - acc: 0.0014 - val_loss: 34667.0860 - val_acc: 0.0021
Epoch 12/50
4290/4290 [==============================] - 1s 177us/step - loss: 35033.8439 - acc: 0.0014 - val_loss: 34369.7790 - val_acc: 0.0021
Epoch 13/50
4290/4290 [==============================] - 1s 181us/step - loss: 35027.9403 - acc: 0.0016 - val_loss: 33936.0209 - val_acc: 0.0042
Epoch 14/50
4290/4290 [==============================] - 1s 181us/step - loss: 34762.4567 - acc: 9.3240e-04 - val_loss: 33971.0561 - val_acc: 0.0000e+00
Epoch 15/50
4290/4290 [==============================] - 1s 182us/step - loss: 34920.3602 - acc: 0.0023 - val_loss: 33470.3884 - val_acc: 0.0021
Epoch 16/50
4290/4290 [==============================] - 1s 186us/step - loss: 34677.8582 - acc: 0.0014 - val_loss: 33318.8647 - val_acc: 0.0000e+00
Epoch 17/50
4290/4290 [==============================] - 1s 184us/step - loss: 34398.6335 - acc: 0.0037 - val_loss: 34120.4212 - val_acc: 0.0042
Epoch 18/50
4290/4290 [==============================] - 1s 185us/step - loss: 34455.9469 - acc: 0.0016 - val_loss: 33294.5289 - val_acc: 0.0021
Epoch 19/50
4290/4290 [==============================] - 1s 184us/step - loss: 34108.9397 - acc: 0.0014 - val_loss: 33443.9538 - val_acc: 0.0042
Epoch 20/50
4290/4290 [==============================] - 1s 182us/step - loss: 34088.4563 - acc: 0.0016 - val_loss: 34058.3735 - val_acc: 0.0000e+00
Epoch 21/50
4290/4290 [==============================] - 1s 176us/step - loss: 34998.5408 - acc: 0.0016 - val_loss: 33668.8879 - val_acc: 0.0021
Epoch 22/50
4290/4290 [==============================] - 1s 189us/step - loss: 34401.3312 - acc: 0.0019 - val_loss: 33181.3708 - val_acc: 0.0021
Epoch 23/50
4290/4290 [==============================] - 1s 184us/step - loss: 34088.7863 - acc: 0.0014 - val_loss: 33552.1761 - val_acc: 0.0000e+00
Epoch 24/50
4290/4290 [==============================] - 1s 184us/step - loss: 33792.2992 - acc: 0.0028 - val_loss: 33500.6426 - val_acc: 0.0000e+00
Epoch 25/50
4290/4290 [==============================] - 1s 181us/step - loss: 34228.1798 - acc: 0.0023 - val_loss: 33386.8597 - val_acc: 0.0000e+00
Epoch 26/50
4290/4290 [==============================] - 1s 184us/step - loss: 34100.5171 - acc: 0.0014 - val_loss: 33363.7212 - val_acc: 0.0021
Epoch 27/50
4290/4290 [==============================] - 1s 188us/step - loss: 33712.5686 - acc: 0.0016 - val_loss: 33622.6387 - val_acc: 0.0000e+00
Epoch 28/50
4290/4290 [==============================] - 1s 185us/step - loss: 33920.3472 - acc: 0.0012 - val_loss: 33207.3417 - val_acc: 0.0042
Epoch 29/50
4290/4290 [==============================] - 1s 183us/step - loss: 33661.2482 - acc: 4.6620e-04 - val_loss: 34001.6679 - val_acc: 0.0021
Epoch 30/50
4290/4290 [==============================] - 1s 184us/step - loss: 33841.9139 - acc: 0.0021 - val_loss: 33322.1981 - val_acc: 0.0000e+00
Epoch 31/50
4290/4290 [==============================] - 1s 186us/step - loss: 33587.3032 - acc: 0.0016 - val_loss: 33552.1485 - val_acc: 0.0042
Epoch 32/50
4290/4290 [==============================] - 1s 185us/step - loss: 33612.5168 - acc: 0.0023 - val_loss: 33415.8936 - val_acc: 0.0021
Epoch 33/50
4290/4290 [==============================] - 1s 184us/step - loss: 33716.7500 - acc: 0.0021 - val_loss: 33872.8264 - val_acc: 0.0084
Epoch 34/50
4290/4290 [==============================] - 1s 182us/step - loss: 33940.6276 - acc: 4.6620e-04 - val_loss: 33372.4351 - val_acc: 0.0084
Epoch 35/50
4290/4290 [==============================] - 1s 181us/step - loss: 33733.8593 - acc: 0.0021 - val_loss: 33371.7171 - val_acc: 0.0042
Epoch 36/50
4290/4290 [==============================] - 1s 193us/step - loss: 33540.4475 - acc: 0.0028 - val_loss: 32944.7270 - val_acc: 0.0000e+00
Epoch 37/50
4290/4290 [==============================] - 1s 191us/step - loss: 33556.6869 - acc: 0.0028 - val_loss: 32863.3757 - val_acc: 0.0105
Epoch 38/50
4290/4290 [==============================] - 1s 188us/step - loss: 33527.9351 - acc: 0.0023 - val_loss: 33290.6901 - val_acc: 0.0042
Epoch 39/50
4290/4290 [==============================] - 1s 194us/step - loss: 33506.6223 - acc: 0.0037 - val_loss: 33270.8918 - val_acc: 0.0000e+00
Epoch 40/50
4290/4290 [==============================] - 1s 209us/step - loss: 33577.1381 - acc: 0.0021 - val_loss: 33246.7460 - val_acc: 0.0000e+00
Epoch 41/50
4290/4290 [==============================] - 1s 206us/step - loss: 33786.1405 - acc: 0.0016 - val_loss: 33067.2583 - val_acc: 0.0021
Epoch 42/50
4290/4290 [==============================] - 1s 216us/step - loss: 33494.4218 - acc: 0.0012 - val_loss: 33062.0611 - val_acc: 0.0042
Epoch 43/50
4290/4290 [==============================] - 1s 202us/step - loss: 33269.2903 - acc: 0.0033 - val_loss: 33000.2493 - val_acc: 0.0042
Epoch 44/50
4290/4290 [==============================] - 1s 221us/step - loss: 33191.8542 - acc: 0.0019 - val_loss: 33111.1757 - val_acc: 0.0000e+00
Epoch 45/50
4290/4290 [==============================] - 1s 302us/step - loss: 33419.9152 - acc: 0.0028 - val_loss: 33739.4054 - val_acc: 0.0021
Epoch 46/50
4290/4290 [==============================] - 1s 177us/step - loss: 33123.2185 - acc: 6.9930e-04 - val_loss: 32576.6680 - val_acc: 0.0042
Epoch 47/50
4290/4290 [==============================] - 1s 161us/step - loss: 33055.7176 - acc: 0.0021 - val_loss: 32913.0260 - val_acc: 0.0000e+00
Epoch 48/50
4290/4290 [==============================] - 1s 178us/step - loss: 32992.4615 - acc: 0.0016 - val_loss: 32748.1545 - val_acc: 0.0042
Epoch 49/50
4290/4290 [==============================] - 1s 161us/step - loss: 32861.3414 - acc: 0.0016 - val_loss: 32881.0411 - val_acc: 0.0000e+00
Epoch 50/50
4290/4290 [==============================] - 1s 169us/step - loss: 32942.0875 - acc: 0.0023 - val_loss: 32793.0495 - val_acc: 0.0000e+00